
INSERT INTO tags (id, tag, language_id) VALUES (1, 'polska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (2, 'niemcy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (3, 'usa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (4, 'trump', 1);
INSERT INTO tags (id, tag, language_id) VALUES (5, 'merkel', 1);
INSERT INTO tags (id, tag, language_id) VALUES (6, 'kaczyński', 1);
INSERT INTO tags (id, tag, language_id) VALUES (7, 'smog', 1);
INSERT INTO tags (id, tag, language_id) VALUES (8, 'ustawa antysmogowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (9, 'ustawa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (10, 'gazprom', 1);
INSERT INTO tags (id, tag, language_id) VALUES (11, 'nordstream2', 1);
INSERT INTO tags (id, tag, language_id) VALUES (12, 'rosja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (13, 'gaz', 1);
INSERT INTO tags (id, tag, language_id) VALUES (494, 'kuratorium oświaty', 1);
INSERT INTO tags (id, tag, language_id) VALUES (495, 'luwr', 1);
INSERT INTO tags (id, tag, language_id) VALUES (16, 'litwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (17, 'orlen', 1);
INSERT INTO tags (id, tag, language_id) VALUES (18, 'transport kolejowy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (19, 'biznes', 1);
INSERT INTO tags (id, tag, language_id) VALUES (24, 'unia europejska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (25, 'ue', 1);
INSERT INTO tags (id, tag, language_id) VALUES (26, 'francja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (27, 'wielka brytania', 1);
INSERT INTO tags (id, tag, language_id) VALUES (28, 'brexit', 1);
INSERT INTO tags (id, tag, language_id) VALUES (29, 'keystone', 1);
INSERT INTO tags (id, tag, language_id) VALUES (30, 'pipeline', 1);
INSERT INTO tags (id, tag, language_id) VALUES (31, 'rurociąg', 1);
INSERT INTO tags (id, tag, language_id) VALUES (32, 'lakota', 1);
INSERT INTO tags (id, tag, language_id) VALUES (34, 'vat', 1);
INSERT INTO tags (id, tag, language_id) VALUES (35, 'zmiany w VAT', 1);
INSERT INTO tags (id, tag, language_id) VALUES (36, 'split payment', 1);
INSERT INTO tags (id, tag, language_id) VALUES (37, 'podatki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (38, 'pis', 1);
INSERT INTO tags (id, tag, language_id) VALUES (39, 'kadencyjność', 1);
INSERT INTO tags (id, tag, language_id) VALUES (40, 'samorządy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (41, 'zmiany w ordynacji', 1);
INSERT INTO tags (id, tag, language_id) VALUES (42, 'ordynacja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (43, 'may', 1);
INSERT INTO tags (id, tag, language_id) VALUES (44, 'theresa may', 1);
INSERT INTO tags (id, tag, language_id) VALUES (45, 'wolny handel', 1);
INSERT INTO tags (id, tag, language_id) VALUES (46, 'syria', 1);
INSERT INTO tags (id, tag, language_id) VALUES (47, 'nato', 1);
INSERT INTO tags (id, tag, language_id) VALUES (48, 'bułgaria', 1);
INSERT INTO tags (id, tag, language_id) VALUES (49, 'prezydent', 1);
INSERT INTO tags (id, tag, language_id) VALUES (50, 'rumen radew', 1);
INSERT INTO tags (id, tag, language_id) VALUES (51, 'sankcje', 1);
INSERT INTO tags (id, tag, language_id) VALUES (52, 'premier', 1);
INSERT INTO tags (id, tag, language_id) VALUES (53, 'miedwiediew', 1);
INSERT INTO tags (id, tag, language_id) VALUES (54, 'meksyk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (55, 'nafta', 1);
INSERT INTO tags (id, tag, language_id) VALUES (56, 'enrique pena', 1);
INSERT INTO tags (id, tag, language_id) VALUES (57, 'wizyty głów', 1);
INSERT INTO tags (id, tag, language_id) VALUES (58, 'mur', 1);
INSERT INTO tags (id, tag, language_id) VALUES (59, 'cła', 1);
INSERT INTO tags (id, tag, language_id) VALUES (60, 'uk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (61, 'assad', 1);
INSERT INTO tags (id, tag, language_id) VALUES (62, 'le pen', 1);
INSERT INTO tags (id, tag, language_id) VALUES (63, 'nowy świat', 1);
INSERT INTO tags (id, tag, language_id) VALUES (64, 'front narodowy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (65, 'obamacare', 1);
INSERT INTO tags (id, tag, language_id) VALUES (66, 'austerity', 1);
INSERT INTO tags (id, tag, language_id) VALUES (67, 'cięcia wydatków', 1);
INSERT INTO tags (id, tag, language_id) VALUES (68, 'morawiecki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (69, 'centralny rejestr faktur', 1);
INSERT INTO tags (id, tag, language_id) VALUES (70, 'gospodarka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (33, 'ministerstwo finansów', 1);
INSERT INTO tags (id, tag, language_id) VALUES (71, 'wsieci', 1);
INSERT INTO tags (id, tag, language_id) VALUES (72, 'bydgoszcz', 1);
INSERT INTO tags (id, tag, language_id) VALUES (73, 'warszawa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (74, 'reprywatyzacja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (75, 'zwierzęta', 1);
INSERT INTO tags (id, tag, language_id) VALUES (76, 'onz', 1);
INSERT INTO tags (id, tag, language_id) VALUES (77, 'uchodźcy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (78, 'węgry', 1);
INSERT INTO tags (id, tag, language_id) VALUES (79, 'migranci', 1);
INSERT INTO tags (id, tag, language_id) VALUES (80, 'imigranci', 1);
INSERT INTO tags (id, tag, language_id) VALUES (81, 'szwecja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (82, 'wojsko', 1);
INSERT INTO tags (id, tag, language_id) VALUES (83, 'cyberatak', 1);
INSERT INTO tags (id, tag, language_id) VALUES (84, 'wicekanclerz', 1);
INSERT INTO tags (id, tag, language_id) VALUES (85, 'kryzys migracyjny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (86, 'orwell', 1);
INSERT INTO tags (id, tag, language_id) VALUES (87, 'post-prawda', 1);
INSERT INTO tags (id, tag, language_id) VALUES (88, 'finlandia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (89, 'demografia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (90, 'statystyki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (91, 'ukraina', 1);
INSERT INTO tags (id, tag, language_id) VALUES (92, 'cmentarz', 1);
INSERT INTO tags (id, tag, language_id) VALUES (93, 'cmentarz wojenny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (94, 'siły zbrojne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (95, 'terroryzm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (96, 'spd', 1);
INSERT INTO tags (id, tag, language_id) VALUES (97, 'wybory parlamentarne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (98, 'manewry', 1);
INSERT INTO tags (id, tag, language_id) VALUES (99, 'włochy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (100, 'trybunał', 1);
INSERT INTO tags (id, tag, language_id) VALUES (101, 'parlament', 1);
INSERT INTO tags (id, tag, language_id) VALUES (102, 'chiny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (103, 'konflikt', 1);
INSERT INTO tags (id, tag, language_id) VALUES (104, 'wyspy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (105, 'demokraci', 1);
INSERT INTO tags (id, tag, language_id) VALUES (106, 'pit', 1);
INSERT INTO tags (id, tag, language_id) VALUES (107, 'urząd skarbowy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (108, 'auchan', 1);
INSERT INTO tags (id, tag, language_id) VALUES (109, 'kontrola', 1);
INSERT INTO tags (id, tag, language_id) VALUES (110, 'inspekcja pracy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (111, 'praca', 1);
INSERT INTO tags (id, tag, language_id) VALUES (112, 'pkb', 1);
INSERT INTO tags (id, tag, language_id) VALUES (113, 'inwestycje publiczne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (114, 'przewidywania', 1);
INSERT INTO tags (id, tag, language_id) VALUES (115, 'transport', 1);
INSERT INTO tags (id, tag, language_id) VALUES (116, 'umowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (117, 'górnictwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (118, 'węgiel', 1);
INSERT INTO tags (id, tag, language_id) VALUES (119, 'innowacje', 1);
INSERT INTO tags (id, tag, language_id) VALUES (120, 'energia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (121, 'surowce', 1);
INSERT INTO tags (id, tag, language_id) VALUES (122, 'sąd', 1);
INSERT INTO tags (id, tag, language_id) VALUES (123, 'pge', 1);
INSERT INTO tags (id, tag, language_id) VALUES (124, 'wyrok sądowy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (125, 'raport', 1);
INSERT INTO tags (id, tag, language_id) VALUES (126, 'shell', 1);
INSERT INTO tags (id, tag, language_id) VALUES (127, 'morze północne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (128, 'rafineria', 1);
INSERT INTO tags (id, tag, language_id) VALUES (129, 'aktywa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (130, 'transakcja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (131, 'sejm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (132, 'deportacje', 1);
INSERT INTO tags (id, tag, language_id) VALUES (133, 'muzułmanie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (134, 'putin', 1);
INSERT INTO tags (id, tag, language_id) VALUES (135, 'rozmowy głów', 1);
INSERT INTO tags (id, tag, language_id) VALUES (136, 'porozumienie z mińska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (137, 'kod', 1);
INSERT INTO tags (id, tag, language_id) VALUES (138, 'kijowski', 1);
INSERT INTO tags (id, tag, language_id) VALUES (139, 'wybory samorządowe', 1);
INSERT INTO tags (id, tag, language_id) VALUES (140, 'wybory', 1);
INSERT INTO tags (id, tag, language_id) VALUES (141, 'bezpieczeństwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (142, 'misiewicz', 1);
INSERT INTO tags (id, tag, language_id) VALUES (143, 'szydło', 1);
INSERT INTO tags (id, tag, language_id) VALUES (144, 'mon', 1);
INSERT INTO tags (id, tag, language_id) VALUES (145, 'bor', 1);
INSERT INTO tags (id, tag, language_id) VALUES (146, 'szef bor', 1);
INSERT INTO tags (id, tag, language_id) VALUES (147, 'wizy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (148, 'mielec', 1);
INSERT INTO tags (id, tag, language_id) VALUES (149, 'cba', 1);
INSERT INTO tags (id, tag, language_id) VALUES (150, 'przetarg na śmigłowce', 1);
INSERT INTO tags (id, tag, language_id) VALUES (151, 'korupcja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (152, 'kanada', 1);
INSERT INTO tags (id, tag, language_id) VALUES (153, 'protekcjonizm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (154, 'kgb', 1);
INSERT INTO tags (id, tag, language_id) VALUES (155, 'tajemnicza śmierć', 1);
INSERT INTO tags (id, tag, language_id) VALUES (156, 'szef kgb', 1);
INSERT INTO tags (id, tag, language_id) VALUES (157, 'materiały kompromitujące trumpa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (158, 'izrael', 1);
INSERT INTO tags (id, tag, language_id) VALUES (159, 'iran', 1);
INSERT INTO tags (id, tag, language_id) VALUES (160, 'dekret', 1);
INSERT INTO tags (id, tag, language_id) VALUES (161, 'gorbaczow', 1);
INSERT INTO tags (id, tag, language_id) VALUES (162, 'groźba wojny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (163, 'donbas', 1);
INSERT INTO tags (id, tag, language_id) VALUES (164, 'donieck', 1);
INSERT INTO tags (id, tag, language_id) VALUES (165, 'separatyzm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (166, 'wojna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (167, 'konflikt ukraiński', 1);
INSERT INTO tags (id, tag, language_id) VALUES (168, 'protesty', 1);
INSERT INTO tags (id, tag, language_id) VALUES (169, 'muslim ban', 1);
INSERT INTO tags (id, tag, language_id) VALUES (172, 'reforma oświaty', 1);
INSERT INTO tags (id, tag, language_id) VALUES (173, 'znp', 1);
INSERT INTO tags (id, tag, language_id) VALUES (174, 'mafia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (175, 'cbś', 1);
INSERT INTO tags (id, tag, language_id) VALUES (176, 'autostrada', 1);
INSERT INTO tags (id, tag, language_id) VALUES (177, 'ograniczenie prędkości', 1);
INSERT INTO tags (id, tag, language_id) VALUES (178, 'awdijiwka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (179, 'roaming', 1);
INSERT INTO tags (id, tag, language_id) VALUES (180, 'parlament europejski', 1);
INSERT INTO tags (id, tag, language_id) VALUES (181, 'telefony', 1);
INSERT INTO tags (id, tag, language_id) VALUES (182, 'fundusze unijne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (183, 'abw', 1);
INSERT INTO tags (id, tag, language_id) VALUES (184, 'frankowicze', 1);
INSERT INTO tags (id, tag, language_id) VALUES (185, 'banki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (186, 'kredyty walutowe', 1);
INSERT INTO tags (id, tag, language_id) VALUES (187, 'kredyty', 1);
INSERT INTO tags (id, tag, language_id) VALUES (188, 'ustawa metropolitalna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (189, 'wyłudzenia vat', 1);
INSERT INTO tags (id, tag, language_id) VALUES (190, 'rumunia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (191, 'rząd', 1);
INSERT INTO tags (id, tag, language_id) VALUES (192, 'centralna baza rachunków', 1);
INSERT INTO tags (id, tag, language_id) VALUES (193, 'śledzenie kont bankowych', 1);
INSERT INTO tags (id, tag, language_id) VALUES (194, 'konta bankowe', 1);
INSERT INTO tags (id, tag, language_id) VALUES (195, 'powiększenie warszawy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (196, 'fsb', 1);
INSERT INTO tags (id, tag, language_id) VALUES (197, 'śmierć', 1);
INSERT INTO tags (id, tag, language_id) VALUES (198, 'policja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (199, 'prokuratura', 1);
INSERT INTO tags (id, tag, language_id) VALUES (200, 'rasizm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (201, 'aleppo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (202, 'polityka wobec uchodźców', 1);
INSERT INTO tags (id, tag, language_id) VALUES (203, 'prawnicy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (204, 'wolność', 1);
INSERT INTO tags (id, tag, language_id) VALUES (205, 'knf', 1);
INSERT INTO tags (id, tag, language_id) VALUES (206, 'myśliwi', 1);
INSERT INTO tags (id, tag, language_id) VALUES (207, 'ruch przeciw mysliwym', 1);
INSERT INTO tags (id, tag, language_id) VALUES (208, 'atak terrorystyczny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (209, 'islam', 1);
INSERT INTO tags (id, tag, language_id) VALUES (210, 'psl', 1);
INSERT INTO tags (id, tag, language_id) VALUES (211, 'anty-pis', 1);
INSERT INTO tags (id, tag, language_id) VALUES (212, 'pocisk balistyczny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (213, 'porozumienie nuklearne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (214, 'broń nuklearna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (215, 'region pomorski', 1);
INSERT INTO tags (id, tag, language_id) VALUES (216, 'przewodniczący', 1);
INSERT INTO tags (id, tag, language_id) VALUES (217, 'filipiny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (218, 'wojna narkotykowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (219, 'poznań', 1);
INSERT INTO tags (id, tag, language_id) VALUES (220, 'skarb państwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (221, 'kościół', 1);
INSERT INTO tags (id, tag, language_id) VALUES (222, 'odszkodowania', 1);
INSERT INTO tags (id, tag, language_id) VALUES (223, 'grypa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (224, 'strajk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (225, 'reforma edukacji', 1);
INSERT INTO tags (id, tag, language_id) VALUES (226, 'brudna kampania', 1);
INSERT INTO tags (id, tag, language_id) VALUES (227, 'oszustwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (228, 'sąd najwyższy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (229, 'odwołanie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (230, 'minister sprawiedliwości', 1);
INSERT INTO tags (id, tag, language_id) VALUES (231, 'prokurator generalny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (232, 'krytyka trumpa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (233, 'zaostrzenie polityki migracyjnej', 1);
INSERT INTO tags (id, tag, language_id) VALUES (234, 'czeczenia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (235, 'kadyrow', 1);
INSERT INTO tags (id, tag, language_id) VALUES (236, 'grozny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (237, 'zamach', 1);
INSERT INTO tags (id, tag, language_id) VALUES (238, 'rosyjskie służby specjalne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (239, 'japonia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (240, 'australia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (241, 'elektroniczny nadzór', 1);
INSERT INTO tags (id, tag, language_id) VALUES (242, 'walka z terroryzmem', 1);
INSERT INTO tags (id, tag, language_id) VALUES (243, 'krym', 1);
INSERT INTO tags (id, tag, language_id) VALUES (244, 'karambol', 1);
INSERT INTO tags (id, tag, language_id) VALUES (245, 'śląsk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (246, 'sopot', 1);
INSERT INTO tags (id, tag, language_id) VALUES (247, 'gdańsk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (248, 'referendum', 1);
INSERT INTO tags (id, tag, language_id) VALUES (249, 'pedofilia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (250, 'przepisy drogowe', 1);
INSERT INTO tags (id, tag, language_id) VALUES (251, 'brd', 1);
INSERT INTO tags (id, tag, language_id) VALUES (252, 'ministerstwo infrastruktury', 1);
INSERT INTO tags (id, tag, language_id) VALUES (253, 'pomoc', 1);
INSERT INTO tags (id, tag, language_id) VALUES (254, 'nik', 1);
INSERT INTO tags (id, tag, language_id) VALUES (255, 'kolej', 1);
INSERT INTO tags (id, tag, language_id) VALUES (256, 'stan techniczny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (257, 'romowie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (258, 'limanowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (259, 'ptasia grypa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (260, 'wrocław', 1);
INSERT INTO tags (id, tag, language_id) VALUES (261, 'kury', 1);
INSERT INTO tags (id, tag, language_id) VALUES (262, 'ruch drogowy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (263, 'bójka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (264, 'zakopane', 1);
INSERT INTO tags (id, tag, language_id) VALUES (265, 'ukraińcy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (266, 'zachowania ksenofobiczne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (267, 'wypadek drogowy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (268, 'wrak tupolewa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (269, 'msz', 1);
INSERT INTO tags (id, tag, language_id) VALUES (270, 'międzynarodowy trybunał sprawiedliwości', 1);
INSERT INTO tags (id, tag, language_id) VALUES (271, 'skargi', 1);
INSERT INTO tags (id, tag, language_id) VALUES (272, 'lech wałęsa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (273, 'sb', 1);
INSERT INTO tags (id, tag, language_id) VALUES (274, 'bolek', 1);
INSERT INTO tags (id, tag, language_id) VALUES (275, 'region opolski', 1);
INSERT INTO tags (id, tag, language_id) VALUES (276, 'krajowa rada sądownictwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (277, 'zmiany w sądownictwie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (278, 'reforma sądownictwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (279, 'demonstracje', 1);
INSERT INTO tags (id, tag, language_id) VALUES (280, 'żagań', 1);
INSERT INTO tags (id, tag, language_id) VALUES (281, 'podwyżki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (282, 'nauczyciele', 1);
INSERT INTO tags (id, tag, language_id) VALUES (283, 'waloryzacja płac', 1);
INSERT INTO tags (id, tag, language_id) VALUES (284, 'minister edukacji', 1);
INSERT INTO tags (id, tag, language_id) VALUES (285, 'wiceminister finansów', 1);
INSERT INTO tags (id, tag, language_id) VALUES (286, 'dymisja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (287, 'afera', 1);
INSERT INTO tags (id, tag, language_id) VALUES (288, 'nowoczesna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (289, 'trybunał konstytucyjny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (290, 'łódź', 1);
INSERT INTO tags (id, tag, language_id) VALUES (291, 'zarząd', 1);
INSERT INTO tags (id, tag, language_id) VALUES (292, 'radom', 1);
INSERT INTO tags (id, tag, language_id) VALUES (293, 'platforma obywatelska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (294, 'wniosek o referendum', 1);
INSERT INTO tags (id, tag, language_id) VALUES (295, 'grupa v4', 1);
INSERT INTO tags (id, tag, language_id) VALUES (296, 'grupa wyszehradzka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (297, 'częstochowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (298, 'podział administracyjny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (299, 'men', 1);
INSERT INTO tags (id, tag, language_id) VALUES (300, '500+', 1);
INSERT INTO tags (id, tag, language_id) VALUES (301, 'komisja etyki poselskiej', 1);
INSERT INTO tags (id, tag, language_id) VALUES (302, 'posłowie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (303, 'pieniądze', 1);
INSERT INTO tags (id, tag, language_id) VALUES (304, 'ułaskawienie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (305, 'region łódzki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (306, 'dolny śląsk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (307, 'biała księga', 1);
INSERT INTO tags (id, tag, language_id) VALUES (308, 'morze czarne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (309, 'afganistan', 1);
INSERT INTO tags (id, tag, language_id) VALUES (310, 'ltiwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (311, 'wschodnia flanka nato', 1);
INSERT INTO tags (id, tag, language_id) VALUES (312, 'rozejm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (313, 'walka z korupcją', 1);
INSERT INTO tags (id, tag, language_id) VALUES (314, 'komisja europejska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (315, 'zjednoczone emiraty arabskie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (316, 'zachodni brzeg', 1);
INSERT INTO tags (id, tag, language_id) VALUES (317, 'osadnicy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (318, 'palestyna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (319, 'bałkany', 1);
INSERT INTO tags (id, tag, language_id) VALUES (320, 'armia fińska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (321, 'skandal', 1);
INSERT INTO tags (id, tag, language_id) VALUES (322, 'fundusze publiczne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (323, 'prawica', 1);
INSERT INTO tags (id, tag, language_id) VALUES (324, 'gruzja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (325, 'papież', 1);
INSERT INTO tags (id, tag, language_id) VALUES (326, 'antysemityzm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (327, 'incydenty', 1);
INSERT INTO tags (id, tag, language_id) VALUES (328, 'szkocja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (329, 'niepodległość', 1);
INSERT INTO tags (id, tag, language_id) VALUES (330, 'rada europejska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (331, 'tusk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (332, 'libia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (333, 'opozycja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (334, 'lewica', 1);
INSERT INTO tags (id, tag, language_id) VALUES (335, 'wybory prezydenckie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (336, 'zmiany w podatkach', 1);
INSERT INTO tags (id, tag, language_id) VALUES (337, 'elektrownia atomowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (338, 'budowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (339, 'sondaże', 1);
INSERT INTO tags (id, tag, language_id) VALUES (340, 'turcja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (341, 'jemen', 1);
INSERT INTO tags (id, tag, language_id) VALUES (342, 'szczyt ue', 1);
INSERT INTO tags (id, tag, language_id) VALUES (343, 'woda', 1);
INSERT INTO tags (id, tag, language_id) VALUES (344, 'konflikt syryjski', 1);
INSERT INTO tags (id, tag, language_id) VALUES (345, 'ar-rakka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (346, 'daesh', 1);
INSERT INTO tags (id, tag, language_id) VALUES (347, 'norwegia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (348, 'wywiad', 1);
INSERT INTO tags (id, tag, language_id) VALUES (349, 'benelux', 1);
INSERT INTO tags (id, tag, language_id) VALUES (350, 'reforma ue', 1);
INSERT INTO tags (id, tag, language_id) VALUES (351, 'facebook', 1);
INSERT INTO tags (id, tag, language_id) VALUES (352, 'mowa nienawiści', 1);
INSERT INTO tags (id, tag, language_id) VALUES (353, 'neonazizm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (354, 'bomba', 1);
INSERT INTO tags (id, tag, language_id) VALUES (355, 'departament stanu', 1);
INSERT INTO tags (id, tag, language_id) VALUES (356, 'kapitalizm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (357, 'szpiegostwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (358, 'ługańsk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (359, 'ukraińskie służby specjalne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (360, 'białoruś', 1);
INSERT INTO tags (id, tag, language_id) VALUES (361, 'blexit', 1);
INSERT INTO tags (id, tag, language_id) VALUES (362, 'poroszenko', 1);
INSERT INTO tags (id, tag, language_id) VALUES (363, 'jordania', 1);
INSERT INTO tags (id, tag, language_id) VALUES (364, 'holandia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (365, 'korea południowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (366, 'csu', 1);
INSERT INTO tags (id, tag, language_id) VALUES (367, 'bawaria', 1);
INSERT INTO tags (id, tag, language_id) VALUES (368, 'kanclerz', 1);
INSERT INTO tags (id, tag, language_id) VALUES (369, 'jugosławia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (370, 'zbrodnia w srebrenicy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (371, 'belgrad', 1);
INSERT INTO tags (id, tag, language_id) VALUES (372, 'bośnia i hercegowina', 1);
INSERT INTO tags (id, tag, language_id) VALUES (373, 'serbia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (374, 'egipt', 1);
INSERT INTO tags (id, tag, language_id) VALUES (375, 'półwysep synaj', 1);
INSERT INTO tags (id, tag, language_id) VALUES (376, 'hiszpania', 1);
INSERT INTO tags (id, tag, language_id) VALUES (377, 'katalonia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (378, 'zabójstwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (379, 'europa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (380, 'canada', 1);
INSERT INTO tags (id, tag, language_id) VALUES (381, 'quebec', 1);
INSERT INTO tags (id, tag, language_id) VALUES (382, 'islamizm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (383, 'strzelanina', 1);
INSERT INTO tags (id, tag, language_id) VALUES (384, 'agencja bezpieczeństwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (385, 'pomniki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (386, 'smoleńsk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (387, 'wałęsa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (388, 'ministerstwo spraw zagranicznych', 1);
INSERT INTO tags (id, tag, language_id) VALUES (389, 'służba zagraniczna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (390, 'zmiany', 1);
INSERT INTO tags (id, tag, language_id) VALUES (391, 'trybunał sprawiedliwości', 1);
INSERT INTO tags (id, tag, language_id) VALUES (392, 'amber gold', 1);
INSERT INTO tags (id, tag, language_id) VALUES (393, 'dowództwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (394, 'stanowisko', 1);
INSERT INTO tags (id, tag, language_id) VALUES (395, 'ipn', 1);
INSERT INTO tags (id, tag, language_id) VALUES (396, 'walka ze smogiem', 1);
INSERT INTO tags (id, tag, language_id) VALUES (397, 'reforma krs', 1);
INSERT INTO tags (id, tag, language_id) VALUES (398, 'słowacja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (399, 'bolesławiec', 1);
INSERT INTO tags (id, tag, language_id) VALUES (400, 'maluch+', 1);
INSERT INTO tags (id, tag, language_id) VALUES (401, 'przyszłość unii europejskiej', 1);
INSERT INTO tags (id, tag, language_id) VALUES (402, 'kancelaria prezydenta', 1);
INSERT INTO tags (id, tag, language_id) VALUES (403, 'stonoga', 1);
INSERT INTO tags (id, tag, language_id) VALUES (404, 'afera taśmowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (405, 'ministerstwo środowiska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (406, 'puszcza', 1);
INSERT INTO tags (id, tag, language_id) VALUES (407, 'nieprzestrzeganie prawa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (408, 'bundestag', 1);
INSERT INTO tags (id, tag, language_id) VALUES (409, 'apple', 1);
INSERT INTO tags (id, tag, language_id) VALUES (410, 'google', 1);
INSERT INTO tags (id, tag, language_id) VALUES (411, 'wyjście z ue', 1);
INSERT INTO tags (id, tag, language_id) VALUES (412, 'żołnierze wyklęci', 1);
INSERT INTO tags (id, tag, language_id) VALUES (413, 'nastroje nacjonalistyczne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (414, 'radykalizacja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (415, ' pis', 1);
INSERT INTO tags (id, tag, language_id) VALUES (416, 'przyszłość ue', 1);
INSERT INTO tags (id, tag, language_id) VALUES (417, 'zamachowiec', 1);
INSERT INTO tags (id, tag, language_id) VALUES (418, 'paryż', 1);
INSERT INTO tags (id, tag, language_id) VALUES (419, 'zamieszki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (420, 'hajnówka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (421, 'słupsk', 1);
INSERT INTO tags (id, tag, language_id) VALUES (422, 'marihuana', 1);
INSERT INTO tags (id, tag, language_id) VALUES (423, 'marihuana medyczna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (424, 'kukiz''15', 1);
INSERT INTO tags (id, tag, language_id) VALUES (425, 'łapówka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (426, 'studia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (427, 'ministerstwo nauki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (428, 'asotthalom', 1);
INSERT INTO tags (id, tag, language_id) VALUES (429, 'homoseksualizm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (430, 'społeczeństwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (431, 'samochody', 1);
INSERT INTO tags (id, tag, language_id) VALUES (432, 'wypożyczalnie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (433, 'car sharing', 1);
INSERT INTO tags (id, tag, language_id) VALUES (434, 'samochody elektryczne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (435, 'agencja towarzyska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (436, 'handel ludźmi', 1);
INSERT INTO tags (id, tag, language_id) VALUES (437, 'rzeszów', 1);
INSERT INTO tags (id, tag, language_id) VALUES (438, 'straż graniczna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (439, 'atak na tle rasowym', 1);
INSERT INTO tags (id, tag, language_id) VALUES (440, 'lublin', 1);
INSERT INTO tags (id, tag, language_id) VALUES (441, 'białystok', 1);
INSERT INTO tags (id, tag, language_id) VALUES (442, 'chuligaństwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (443, 'kraków', 1);
INSERT INTO tags (id, tag, language_id) VALUES (444, 'przemoc domowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (445, 'mniejszość niemiecka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (446, 'legionowo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (447, 'pomoc humanitarna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (448, 'penelope gate', 1);
INSERT INTO tags (id, tag, language_id) VALUES (449, 'awdijiwca', 1);
INSERT INTO tags (id, tag, language_id) VALUES (450, 'cdu', 1);
INSERT INTO tags (id, tag, language_id) VALUES (451, 'wolność słowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (452, 'bandera', 1);
INSERT INTO tags (id, tag, language_id) VALUES (453, 'kreml', 1);
INSERT INTO tags (id, tag, language_id) VALUES (454, 'rozszerzenie nato', 1);
INSERT INTO tags (id, tag, language_id) VALUES (455, 'kabul', 1);
INSERT INTO tags (id, tag, language_id) VALUES (456, 'rukłe', 1);
INSERT INTO tags (id, tag, language_id) VALUES (457, 'nielegalne finansowanie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (458, 'kampania wyborcza', 1);
INSERT INTO tags (id, tag, language_id) VALUES (459, 'fox news', 1);
INSERT INTO tags (id, tag, language_id) VALUES (460, 'chamenei', 1);
INSERT INTO tags (id, tag, language_id) VALUES (461, 'internet', 1);
INSERT INTO tags (id, tag, language_id) VALUES (462, 'ograniczenia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (463, 'austria', 1);
INSERT INTO tags (id, tag, language_id) VALUES (464, 'estonia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (465, 'uzbrojenie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (466, 'broń', 1);
INSERT INTO tags (id, tag, language_id) VALUES (467, 'relokacja uchodźców', 1);
INSERT INTO tags (id, tag, language_id) VALUES (468, 'osadnictwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (469, 'al-bab', 1);
INSERT INTO tags (id, tag, language_id) VALUES (470, 'negocjacje', 1);
INSERT INTO tags (id, tag, language_id) VALUES (471, 'lewiatan', 1);
INSERT INTO tags (id, tag, language_id) VALUES (472, 'nierówności', 1);
INSERT INTO tags (id, tag, language_id) VALUES (473, 'ropa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (474, 'niezależność energetyczna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (475, 'marynarka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (476, 'katar', 1);
INSERT INTO tags (id, tag, language_id) VALUES (477, 'linie lotnicze', 1);
INSERT INTO tags (id, tag, language_id) VALUES (478, 'autostrady', 1);
INSERT INTO tags (id, tag, language_id) VALUES (479, 'partnerstwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (480, 'euro', 1);
INSERT INTO tags (id, tag, language_id) VALUES (481, 'polityka handlowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (482, 'ebc', 1);
INSERT INTO tags (id, tag, language_id) VALUES (483, 'lubuskie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (484, 'inflacja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (485, 'nowe technologie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (486, 'maszyny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (487, 'oszczędzanie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (488, 'pracownicy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (489, 'sharing economy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (490, 'honda', 1);
INSERT INTO tags (id, tag, language_id) VALUES (491, 'hitachi', 1);
INSERT INTO tags (id, tag, language_id) VALUES (492, 'wydatki na zbrojenia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (493, 'małopolska', 1);
INSERT INTO tags (id, tag, language_id) VALUES (496, 'opole', 1);
INSERT INTO tags (id, tag, language_id) VALUES (497, 'schengen', 1);
INSERT INTO tags (id, tag, language_id) VALUES (498, 'relacje społeczne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (499, 'gazy cieplarniane', 1);
INSERT INTO tags (id, tag, language_id) VALUES (500, 'odpady tłuszczowe', 1);
INSERT INTO tags (id, tag, language_id) VALUES (501, 'olej napędowy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (502, 'brześć', 1);
INSERT INTO tags (id, tag, language_id) VALUES (503, 'religia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (504, 'autorytaryzm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (505, 'kryzys', 1);
INSERT INTO tags (id, tag, language_id) VALUES (506, 'nowa zelandia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (507, 'volkswagen', 1);
INSERT INTO tags (id, tag, language_id) VALUES (508, 'pozew', 1);
INSERT INTO tags (id, tag, language_id) VALUES (509, 'fałszowanie', 1);
INSERT INTO tags (id, tag, language_id) VALUES (510, 'pogoda', 1);
INSERT INTO tags (id, tag, language_id) VALUES (511, 'burze śnieżne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (512, 'urzędnicy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (513, 'fake news', 1);
INSERT INTO tags (id, tag, language_id) VALUES (514, 'finanse', 1);
INSERT INTO tags (id, tag, language_id) VALUES (515, 'współpraca', 1);
INSERT INTO tags (id, tag, language_id) VALUES (516, 'mieszkanie+', 1);
INSERT INTO tags (id, tag, language_id) VALUES (517, 'wybuch', 1);
INSERT INTO tags (id, tag, language_id) VALUES (518, 'expose', 1);
INSERT INTO tags (id, tag, language_id) VALUES (519, 'polityka zagraniczna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (520, 'manifestacja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (521, 'irlandia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (522, 'europa wschodnia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (523, 'ceberprzestępstwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (524, 'klauzula sumienia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (525, 'system obrony przeciwrakietowej', 1);
INSERT INTO tags (id, tag, language_id) VALUES (526, 'missisipi', 1);
INSERT INTO tags (id, tag, language_id) VALUES (527, 'kara śmierci', 1);
INSERT INTO tags (id, tag, language_id) VALUES (528, 'al-kaida', 1);
INSERT INTO tags (id, tag, language_id) VALUES (529, 'departament sprawiedliwości', 1);
INSERT INTO tags (id, tag, language_id) VALUES (530, 'tanzania', 1);
INSERT INTO tags (id, tag, language_id) VALUES (531, 'kolonializm', 1);
INSERT INTO tags (id, tag, language_id) VALUES (532, 'upa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (533, 'senat', 1);
INSERT INTO tags (id, tag, language_id) VALUES (534, 'bexit', 1);
INSERT INTO tags (id, tag, language_id) VALUES (535, 'wieża eiffla', 1);
INSERT INTO tags (id, tag, language_id) VALUES (536, 'braniewo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (537, 'strefa ekonomiczna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (538, 'przemysł motoryzacyjny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (539, 'katowice', 1);
INSERT INTO tags (id, tag, language_id) VALUES (540, 'brazylia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (541, 'czarny protest', 1);
INSERT INTO tags (id, tag, language_id) VALUES (542, 'nbp', 1);
INSERT INTO tags (id, tag, language_id) VALUES (543, 'rynek pracy', 1);
INSERT INTO tags (id, tag, language_id) VALUES (544, 'płaca minimalna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (545, 'bloger', 1);
INSERT INTO tags (id, tag, language_id) VALUES (546, 'planowanie przestrzenne', 1);
INSERT INTO tags (id, tag, language_id) VALUES (547, 'obszary pod inwestycje', 1);
INSERT INTO tags (id, tag, language_id) VALUES (548, 'ortodoksyjni żydzi', 1);
INSERT INTO tags (id, tag, language_id) VALUES (549, 'służba wojskowa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (550, 'przestępstwa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (551, 'układ nuklearny', 1);
INSERT INTO tags (id, tag, language_id) VALUES (552, 'naruszenie granic', 1);
INSERT INTO tags (id, tag, language_id) VALUES (553, 'lotnictwo', 1);
INSERT INTO tags (id, tag, language_id) VALUES (554, 'sajdnaja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (555, 'amnesty', 1);
INSERT INTO tags (id, tag, language_id) VALUES (556, 'prawa człowieka', 1);
INSERT INTO tags (id, tag, language_id) VALUES (557, 'reforma konstytucyjna', 1);
INSERT INTO tags (id, tag, language_id) VALUES (558, 'zielona energia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (559, 'oze', 1);
INSERT INTO tags (id, tag, language_id) VALUES (560, 'wiatraki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (561, 'konflikt afgański', 1);
INSERT INTO tags (id, tag, language_id) VALUES (562, 'wypadek', 1);
INSERT INTO tags (id, tag, language_id) VALUES (563, 'oświęcim', 1);
INSERT INTO tags (id, tag, language_id) VALUES (564, 'repolonizacja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (565, 'prasa', 1);
INSERT INTO tags (id, tag, language_id) VALUES (566, 'media', 1);
INSERT INTO tags (id, tag, language_id) VALUES (567, 'powiększenie opola', 1);
INSERT INTO tags (id, tag, language_id) VALUES (568, 'dobrzeń wielki', 1);
INSERT INTO tags (id, tag, language_id) VALUES (569, 'relacje', 1);
INSERT INTO tags (id, tag, language_id) VALUES (570, 'irak', 1);
INSERT INTO tags (id, tag, language_id) VALUES (571, 'słowenia', 1);
INSERT INTO tags (id, tag, language_id) VALUES (572, 'grecja', 1);
INSERT INTO tags (id, tag, language_id) VALUES (573, 'pomoc dla grecji', 1);

SELECT pg_catalog.setval('tags_id_seq', 573, true);